resources:
  - name: factorio-repo
    type: gitRepo
    integration: "trriplejay github"
    versionTemplate:
      sourceName: softsrv/factorio
      branch: master

  - name: factorio-params #seeds
    type: params
    versionTemplate:
      params:
        init_dropletId: "108883768"
        init_snapshotId: ""
      

  - name: digitalocean-creds
    type: integration
    integration: digitalocean-creds

  - name: factorio-hook
    type: webhook
    versionTemplate:
      webhookKey: four-fluffy-feathers-on-a-fiffer-feffer-fef

jobs:
  - name: factorio-controller
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: digitalocean-creds
      - IN: factorio-hook
      - IN: factorio-repo
        switch: off
      - IN: factorio-params
      - TASK:
          name: cycle-do-box
          runtime:
            options:
              env:
                - fVersion: "0.16"
                - snapshotName: "factorio-ss"
                - snapshotId: ""
                - region: sfo2
                - size: s-1vcpu-2gb

          script:
            - pushd $(shipctl get_resource_state factorio-repo)
            - echo "starting..."
            - shipctl copy_file_from_prev_state state.env .
            - if [ -f "state.env" ]; then source state.env; fi
            - >
              if [ "$JOB_TRIGGERED_BY_NAME" == "factorio-hook" ]; then
                HOOK_META=$(shipctl get_resource_meta factorio-hook)
                export response_url=$(shipctl get_json_value "$HOOK_META/version.json" "version.propertyBag.payload.response_url")
                export message=$(shipctl get_json_value "$HOOK_META/version.json" "version.propertyBag.payload.text")
                export slack_user=$(shipctl get_json_value "$HOOK_META/version.json" "version.propertyBag.payload.user_name")
                if [ "$message" == "start" ] && [ -z $snapshotId ]; then
                  ./respond.sh "Skipping start. The server should already be running."
                  export skip=true
                elif [ "$message" == "stop" ] && [ -z $dropletId ]; then
                  ./respond.sh "Skipping stop. The server is already stopped."
                  export skip=true
                fi
              elif [ "$FORCE_ACTION" == "rebuild" ]; then
                echo "forcing rebuild from snapshotId $init_snapshotId"
                export snapshotId="$init_snapshotId"
                export dropletId=""
              elif [ "$FORCE_ACTION" == "destroy" ]; then
                echo "forcing destruction of dropletId $init_dropletId"
                export snapshotId=""
                export dropletId="$init_dropletId"
              fi

            - if [ -z "$skip" ]; then ./cycle.sh; fi
    on_failure:
      script:
        - ./respond.sh "An error occured. see $BUILD_URL for more details"        
            
            
