resources:
  - name: factorio-repo
    type: gitRepo
    integration: "trriplejay github"
    versionTemplate:
      sourceName: softsrv/factorio
      branch: master

  - name: factorio-params #seeds
    type: params
    versionTemplate:
      params:
        init_dropletId: 108875261
        init_snapshotId: 37946678
        action: rebuild
      

  - name: digitalocean-creds
    type: integration
    integration: digitalocean-creds

  - name: factorio-hook
    type: webhook
    versionTemplate:
      webhookKey: four-fluffy-feathers-on-a-fiffer-feffer-fef

jobs:
  - name: factorio-controller
    type: runSh
    steps:
      - IN: digitalocean-creds
      - IN: factorio-hook
      - IN: factorio-repo
        switch: off
      - IN: factorio-params
        switch: off
      - TASK:
          name: cycle-do-box
          runtime:
            options:
              env:
                - fVersion: "0.16"
                - snapshotName: "factorio-ss"
                - snapshotId: ""
                - region: sfo2
                - size: s-1vcpu-2gb

          script:
            - pushd $(shipctl get_resource_state factorio-repo)
            - echo "starting..."
            - shipctl copy_file_from_prev_state state.env .
            - if [ -f "state.env" ]; then source state.env; fi
            - if [ -z "$dropletId" ] && [ -z "$snapshotId" ]; then export dropletId=$init_dropletId; fi
            - >
              if [ "$JOB_TRIGGERED_BY_NAME" == "factorio-params" ]; then 
                if [ "$action" == "rebuild" ]; then
                  export snapshotId=$init_snapshotId
                  export dropletId=""
                elif [ "$action" == "destroy" ]; then
                  export dropletId=$init_dropletId
                  export snapshotId=""
                fi
            - ./cycle.sh
            
            
